<?php

namespace YourVendor\Settings\Cache;

use YourVendor\Settings\Exceptions\SettingsCacheException;

/**
 * Prosty, opcache-friendly cache plikowy.
 *
 * Format pliku:
 *   <?php return ['global' => [...], 'users' => [1 => [...], 2 => [...]]];
 *
 * Klucze globalne żyją pod 'global', per-user pod 'users.<userId>'.
 */
class FileSettingsCache
{
    private bool $loaded = false;

    /** @var array{global: array<string,mixed>, users: array<int,array<string,mixed>>} */
    private array $data = ['global' => [], 'users' => []];

    public function __construct(private readonly string $path) {}

    // -------------------------------------------------------------------------
    // Odczyt
    // -------------------------------------------------------------------------

    public function get(string $key, ?int $userId = null): mixed
    {
        $this->load();

        if ($userId !== null && array_key_exists($key, $this->data['users'][$userId] ?? [])) {
            return $this->data['users'][$userId][$key];
        }

        return $this->data['global'][$key] ?? null;
    }

    public function has(string $key, ?int $userId = null): bool
    {
        $this->load();

        if ($userId !== null && array_key_exists($key, $this->data['users'][$userId] ?? [])) {
            return true;
        }

        return array_key_exists($key, $this->data['global']);
    }

    /**
     * Zwróć wszystkie ustawienia: globalne scalone z per-user (user nadpisuje).
     */
    public function all(?int $userId = null): array
    {
        $this->load();

        $merged = $this->data['global'];

        if ($userId !== null) {
            $merged = array_merge($merged, $this->data['users'][$userId] ?? []);
        }

        return $merged;
    }

    public function isLoaded(): bool
    {
        return $this->loaded;
    }

    public function exists(): bool
    {
        return file_exists($this->path);
    }

    // -------------------------------------------------------------------------
    // Zapis – zawsze przepisuje cały plik
    // -------------------------------------------------------------------------

    public function put(string $key, mixed $value, ?int $userId = null): void
    {
        $this->load();

        if ($userId !== null) {
            $this->data['users'][$userId][$key] = $value;
        } else {
            $this->data['global'][$key] = $value;
        }

        $this->flush();
    }

    public function remove(string $key, ?int $userId = null): void
    {
        $this->load();

        if ($userId !== null) {
            unset($this->data['users'][$userId][$key]);
        } else {
            unset($this->data['global'][$key]);
        }

        $this->flush();
    }

    /**
     * Zastąp całą zawartość cache nowym zestawem danych.
     * Używane przy pełnym przeładowaniu z bazy.
     *
     * @param array<string,mixed>                    $globalSettings
     * @param array<int,array<string,mixed>>         $userSettings
     */
    public function rebuild(array $globalSettings, array $userSettings): void
    {
        $this->data = [
            'global' => $globalSettings,
            'users'  => $userSettings,
        ];
        $this->loaded = true;
        $this->flush();
    }

    public function invalidate(): void
    {
        $this->data   = ['global' => [], 'users' => []];
        $this->loaded = false;

        if (file_exists($this->path)) {
            @unlink($this->path);
        }
    }

    // -------------------------------------------------------------------------
    // Internals
    // -------------------------------------------------------------------------

    private function load(): void
    {
        if ($this->loaded) {
            return;
        }

        if (file_exists($this->path)) {
            $data = @include $this->path;
            if (is_array($data)) {
                $this->data   = $data;
                $this->loaded = true;
                return;
            }
        }

        // Plik nie istnieje lub uszkodzony – będzie potrzebny rebuild z bazy
        $this->loaded = false;
    }

    private function flush(): void
    {
        $dir = dirname($this->path);

        if (!is_dir($dir) && !mkdir($dir, 0755, true)) {
            throw new SettingsCacheException("Nie można utworzyć katalogu cache: {$dir}");
        }

        $export  = var_export($this->data, true);
        $content = "<?php\n\n// Auto-generated by laravel-settings. DO NOT EDIT.\n// Generated at: " . date('Y-m-d H:i:s') . "\n\nreturn {$export};\n";
        $tmp     = $this->path . '.tmp.' . getmypid();

        if (file_put_contents($tmp, $content, LOCK_EX) === false) {
            throw new SettingsCacheException("Nie można zapisać pliku cache: {$this->path}");
        }

        // Atomowy rename – zapobiega odczytaniu half-written file
        if (!rename($tmp, $this->path)) {
            @unlink($tmp);
            throw new SettingsCacheException("Nie można zastąpić pliku cache: {$this->path}");
        }

        // Odśwież opcache jeśli aktywny
        if (function_exists('opcache_invalidate')) {
            opcache_invalidate($this->path, true);
        }
    }
}
